version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
  
  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server
      - SERVER_PORT=5000
      - CUST_ID=1
  
  database:
    # restart: always
    build: database
    links:
      - mongodb
      - rabbitmq
    volumes:
      - ./database:/app
    
    
  mongodb:
    image: mongo
    ports:
      - 27017
