
# FROM postgres:latest
# ENV POSTGRES_PASSWORD=secret
# ENV POSTGRES_USER=username
# ENV POSTGRES_DB=database
# COPY create_fixtures.sql /docker-entrypoint-initdb.d/create_fixtures.sql

FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y postgresql
RUN apt-get install libpq-dev

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install pika && \
    pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]