FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

WORKDIR /app

RUN pip3 install pika
RUN pip3 install pymongo

COPY . /app

ENV PYTHONUNBUFFERED=0

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]
